image: docker:24.0.7

stages:
  - build

variables:
  IMAGE_TAG_BUILDER: $CI_REGISTRY_IMAGE/builder:latest
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DOCKER_BUILDKIT: '1'

build:
  stage: build
  cache:
    - key: next-cache
      paths:
        - .next/cache
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - mkdir -p .next/cache
  script:
    - ls -la .next/cache
    - docker pull $IMAGE_TAG_BUILDER || true
    - docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG_BUILDER -t $IMAGE_TAG_BUILDER --target=builder .
    - docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG_BUILDER -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_BUILDER
    - docker run --rm -iv${PWD}/.next:/host-volume $IMAGE_TAG_BUILDER sh -s "cp -r .next/cache /host-volume"
    - ls -la .next/cache
